### ISSUE TITLE
visualize volume change when hover scrolling sound tiles

### ISSUE THREAD

**Issue by b00dle** [children-of-gazimba/companion-qt-tool#32]
The hover scrolling volume change has seen some good use, yet it is still difficult to make precise changes. We need visual feedback to aid this feature. It might make most sense to have a slider pop up and visualize the change whenever a tile is hover scrolled.

**Comment by hG3n** [comment]
How about simply using the whole tiles background as volume visualization. Once a hover-scroll event has been recognized, the background is filled up to the current volume. This representation is visible for the next __x__ seconds.

![volume_concept](https://user-images.githubusercontent.com/1724808/43536753-ad62af62-95bd-11e8-8a38-0059ecdc0f1b.png)

**Comment by b00dle** [comment]
haha it's funny you mention this now. I was just going to assign this to myself and do exactly that. love it! =)
