### ISSUE TITLE
thumbnails for image browser

### ISSUE THREAD

**Issue by b00dle** [children-of-gazimba/companion-qt-tool#36]
we have seen some complications with the use of the image browser. thumbnails shouldn't only pop up when hovering images, but we need a permanent visualization in the image browser. No one remembers tons of image filenames to identify their resources while in session. succccc.

The implementation of this piece might rely on issue #35

**Comment by hG3n** [comment]
I totally agree! If you don't want to do it by yourself I'd start working on that.

**Comment by b00dle** [comment]
ok, sounds good! You might wanna look at how the tooltip thumbnails are generated on the image list to get an understanding of how the images could be created. Let's not adjust the backend for now, and create them on the fly (when the file list is refreshed). Maybe Qt even has a performant way to visualize thumbnail lists. You can keep the tooltip in for each item, I could see a hover magnification making sense.

**Comment by b00dle** [comment]
#61 done.
